[package]
name = "windows-clipboard"
version = "1.0.0"
authors = ["Sindre Sorhus <sindresorhus@gmail.com>", "Vsevolod Strukchinsky <floatdrop@gmail.com>"]

[dependencies]
clipboard-win = "5.4.0"

# https://github.com/johnthagen/min-sized-rust#optimize-for-size
[profile.release]
opt-level = "z"  # Optimize for size.
lto = true
